### ISSUE TITLE
Geocoder

### ISSUE THREAD

**Issue by willdurand** [michielvandergeest/geocoder#1]
Hi!

You should look at [Geocoder PHP](http://geocoder-php.org/) I guess :)
There is also a [Laravel package](http://geocoder-php.org/GeocoderLaravel/).

**Comment by michielvandergeest** [comment]
@willdurand 

You are right that Geocoder PHP is far more complete and advanced as my package. It looks like a very nice project! 

My package is initially built as a simple Geocoder implementation for personal use and I decided to share it with the world. Not with the intention to be the most complete package ever and replace Geocoder PHP, but as a way to get more experience with package development and sharing open source packages.

I will continue to develop the package over time. If people like to use my package or want to contribute to it, they are very welcome to do so.

Otherwise, if people are looking for a complete Geocoder solution, I would gladly point them to Geocoder PHP :)
